/* AI 情报站 - 实力排行榜数据（每日自动更新） */
window.RANK_UPDATED = "2026-09-25";
window.RANK = {
    models: [
      {name:"Claude Opus 5.5", vendor:"Anthropic（美国）", price:"API $4/$20 每百万", iaa:58, tb:null,
       t:{综合:"S",推理:"S",代码:"S",多模态:"A",长上下文:"S",中文:"B",性价比:"B",开源:"—"},
       note:"2026-09-22 发布，AA 智能指数 v4.3 最高分 58（超越 Fable 5.1 / Astra 的 53）；TB4.0 59.6%（xhigh，与 Astra 并列第一）。价格较 Opus 5 降 20%（$4/$20）。agentic 知识工作领先（AA-Briefcase 1822 Elo）。⚠ 本页 tb 列仍用 TB2.1 旧口径，Opus 5.5 无 TB2.1 公开分，故留空。中文偏弱。"},
      {name:"Claude Fable 5.1", vendor:"Anthropic（美国）", price:"Pro $17–20/月；API $10/$50 每百万", iaa:53, tb:91.4,
       t:{综合:"S",推理:"S",代码:"S",多模态:"A",长上下文:"S",中文:"B",性价比:"C",开源:"—"},
       note:"2026-09-01 发布，AA 智能指数 v4.3 并列第一（53）；TB2.1 第一（91.4%）。⚠ 官方 8/29 已升级 Terminal-Bench v4.0（66 题、难度大幅提升），AA v4.3 起改用 TB4.0：Astra 59.1% > Fable 5.1 52.0% > Opus 5 49.0% > GPT-5.6 Sol 39.9%；本页 TB 列仍为 2.1 旧口径。推理/综合最强，但价格最高、中文偏弱。"},
      {name:"GPT-6 Astra", vendor:"OpenAI（美国）", price:"API $10/$50 每百万", iaa:53, tb:89.9,
       t:{综合:"S",推理:"S",代码:"S",多模态:"A",长上下文:"S",中文:"A",性价比:"C",开源:"—"},
       note:"2026-09-03 发布，号称进入 AGI 时代；AA 指数并列第一（53）、代码 Agent 指数 67；TB4.0 59.1%（max）现居第一。但被定为「关键网络安全」级，目前仅 Daybreak 计划批准者可用，投票榜样本极少。"},
      {name:"Claude Opus 5", vendor:"Anthropic（美国）", price:"Pro $17–20/月；API $5/$25 每百万", iaa:51, tb:89.1,
       t:{综合:"S",推理:"S",代码:"S",多模态:"A",长上下文:"S",中文:"B",性价比:"B",开源:"—"},
       note:"投票榜 coding 冠军（image-to-WebDev 第一），价格仅 Fable 5.1 一半（$5/$25）；TB2.1 89.1%（TB4.0 49.0%）。英文/代码极强，中文偏弱。"},
      {name:"Claude Fable 5", vendor:"Anthropic（美国）", price:"Pro $17–20/月；API $10/$50 每百万", iaa:50, tb:83.1,
       t:{综合:"S",推理:"S",代码:"S",多模态:"A",长上下文:"S",中文:"B",性价比:"C",开源:"—"},
       note:"LMArena 文本盲测长期第一（体感最佳）；AA 50。配 Claude Code 时 SWE-bench Verified 达 95%。综合 S 但价格高。"},
      {name:"GPT-5.6 Sol", vendor:"OpenAI（美国）", price:"Plus $20/月；API $4/$20 每百万", iaa:47, tb:89.5,
       t:{综合:"S",推理:"S",代码:"S",多模态:"A",长上下文:"S",中文:"A",性价比:"B",开源:"—"},
       note:"AA 47、TB2.1 89.5%（与 Astra 同档）；⚠ TB4.0 掉到 39.9%，与 Astra 拉开 19.2 分。代码 Agent 指数 67，生态最全。中文与代码均强，性价比优于 Claude。"},
      {name:"GPT-6 Sol", vendor:"OpenAI（美国）", price:"API $2/$10 每百万", iaa:null, tb:null,
       t:{综合:"S",推理:"S",代码:"S",多模态:"A",长上下文:"S",中文:"A",性价比:"A",开源:"—"},
       note:"2026-09-22 发布，GPT-5.6 Sol 的继任者（Codex / ChatGPT Work，非 Chat；API gpt-6-sol）；较 GPT-5.6 Sol 降价约 50%（约 $2/$10）。⚠ AA 智能指数官方未公布，theairankings 口径约 48，待核实；TB2.1 暂无，tb 列留空。中文与代码均强，性价比提升明显。"},
      {name:"Grok 4.6", vendor:"xAI（美国）", price:"API $2/$6 每百万", iaa:44, tb:88.4,
       t:{综合:"A",推理:"A",代码:"A",多模态:"A",长上下文:"B",中文:"B",性价比:"B",开源:"—"},
       note:"8 月后训练刷新，AA 跳至 44；TB2.1 88.4%。价格低、长任务回合少。中文/长上下文略逊。"},
      {name:"Grok 4.7", vendor:"xAI（美国）", price:"API $2/$6 每百万", iaa:46, tb:null,
       t:{综合:"A",推理:"A",代码:"A",多模态:"A",长上下文:"B",中文:"B",性价比:"B",开源:"—"},
       note:"2026-09-21 正式发布（GA），参数 2.1 万亿；AA 智能指数 v4.3 确认 46.4（xhigh，显示为 46），较 Grok 4.6 的 44 提升约 2 点；TB4.0 24.7%（high）。⚠ 无 TB2.1 公开分，tb 列留空；价格 $2/$6（xAI 定价）。"},
      {name:"Muse Spark 1.3", vendor:"Meta（美国）", price:"闭源（开发者发布）", iaa:48, tb:null,
       t:{综合:"A",推理:"A",代码:"A",多模态:"B",长上下文:"B",中文:"C",性价比:"B",开源:"—"},
       note:"2026-09-02 发布，AA 48（8 点跃升）；开发者发布、无消费端入口；agent 行全面落后（Meta 自家图）；TB4.0 约 33.3%（AA 口径）。英文生态为主。"},
      {name:"GLM-5.3 / GLM-5.3-Flash", vendor:"智谱 Zhipu（中国）", price:"Flash 开源 MIT；API $0.15/$0.50 每百万", iaa:45, tb:84.3,
       t:{综合:"A",推理:"A",代码:"A",多模态:"B",长上下文:"A",中文:"S",性价比:"A",开源:"A"},
       note:"国产综合最强之一；Flash 版 8-26 发布即 MIT 开源、AA 42、性价比之王（列表价 $0.15/$0.50）。中文 S。"},
      {name:"Kimi K3", vendor:"Moonshot AI（中国）", price:"免费商用 / API 低价", iaa:44, tb:85.0,
       t:{综合:"A",推理:"A",代码:"A",多模态:"B",长上下文:"A",中文:"A",性价比:"A",开源:"A"},
       note:"AA 44、Terminal-Bench 85.0；长上下文与中文强，部分权重开源可自部署。"},
      {name:"Gemini 3.8 Flash", vendor:"Google（美国）", price:"API $0.75/$3.75 每百万（2027 起翻倍）", iaa:41, tb:87.6,
       t:{综合:"A",推理:"A",代码:"A",多模态:"S",长上下文:"S",中文:"A",性价比:"A",开源:"—"},
       note:"2026-09-02 发布，Google 当前主力 workhorse；多模态/超长上下文（1M）标杆，TB2.1 87.6%。⚠ TB4.0 仅 19.7%（新榜难度陡增，同模型跌幅最大）。价格友好（限时）。"},
      {name:"Gemini 3.1 Pro", vendor:"Google（美国）", price:"API $2/$12 每百万", iaa:null, tb:null,
       t:{综合:"A",推理:"S",代码:"A",多模态:"A",长上下文:"S",中文:"A",性价比:"B",开源:"—"},
       note:"现仍在售的真正旗舰 Pro（3.5 Pro 一再跳票）；GPQA Diamond 94.3%、ARC-AGI-1 98%。最强纯推理与超长上下文，价格高于 Flash。"},
      {name:"Qwen3.8-Max", vendor:"阿里巴巴（中国）", price:"闭源顶配 / Qwen3.8-Flash-Next 开源", iaa:40, tb:null,
       t:{综合:"A",推理:"A",代码:"A",多模态:"B",长上下文:"A",中文:"A",性价比:"A",开源:"A"},
       note:"Qwen3.8-Max-0902 于 9-2 登 Code Arena WebDev 榜首（1691）；开源 Qwen3.8-Flash-Next 首发 Qwen4 架构。生态最大。"},
      {name:"DeepSeek V4.1-Flash", vendor:"DeepSeek（中国）", price:"限时 API 预览 / 低价", iaa:40, tb:null,
       t:{综合:"B",推理:"B",代码:"A",多模态:"B",长上下文:"B",中文:"A",性价比:"A",开源:"—"},
       note:"2026-09-10 发布，552B MoE（每 token 激活 8–16B）、原生多模态，推理效率大幅提升；AA 指数 40（max，2026-09-13 版）。⚠ 限时 API 预览版，是否开放权重待核实；TB4.0 各家 harness 差异极大（约 11.6%–26.8%），暂不填。"},
      {name:"DeepSeek V4 Pro", vendor:"DeepSeek（中国）", price:"开源免费 / API 低价", iaa:36, tb:78.7,
       t:{综合:"B",推理:"B",代码:"A",多模态:"B",长上下文:"B",中文:"A",性价比:"S",开源:"S"},
       note:"DeepSWE 1.1 80.6%（开源权重最高）；性价比/开源双 S，可完全自部署。综合与英文稍弱。"},
      {name:"Hunyuan 混元", vendor:"腾讯（中国）", price:"Hy4 Preview 开源（Apache 2.0）", iaa:null, tb:null,
       t:{综合:"B",推理:"B",代码:"B",多模态:"B",长上下文:"B",中文:"A",性价比:"B",开源:"A"},
       note:"国产主力，中文与性价比均衡；Hy4 Preview 8-28 开源（770B，Apache 2.0），适合国内合规与本地化。"},
      {name:"Llama 4", vendor:"Meta（美国）", price:"开源权重", iaa:null, tb:null,
       t:{综合:"B",推理:"B",代码:"B",多模态:"B",长上下文:"B",中文:"C",性价比:"B",开源:"S"},
       note:"经典开源底座，生态与工具链最成熟；中文弱，是许多自部署方案的首选底模。"},
      {name:"MiniMax M3", vendor:"MiniMax（中国）", price:"开源权重 / API", iaa:null, tb:null,
       t:{综合:"B",推理:"B",代码:"B",多模态:"B",长上下文:"B",中文:"A",性价比:"B",开源:"A"},
       note:"国产新锐，中文与多模态均衡，已开放部分权重；综合处于第二梯队。"}
    ],
    tools: [
      {name:"Claude Code", model:"默认 Claude Opus 5 / Fable 5", price:"Pro $17–20/月（按 token 计）", tb:89.1, sv:95.0,
       t:{上手:"B",开源:"—"},
       note:"终端优先、harness 最深：1M 上下文、子代理并行、钩子（hooks）可编程。SWE-bench V 95%（Fable 5）、TB2.1 89.1% 标杆；缺点 token 消耗大（约 Codex 3–4 倍），无 IDE 图形界面。"},
      {name:"OpenAI Codex", model:"默认 GPT-5.6 Sol", price:"Plus $20/月", tb:89.5, sv:88.7,
       t:{上手:"B",开源:"—"},
       note:"并行/异步云虚拟机跑任务、git worktree 排队不冲突、自动提 PR；Terminal-Bench 2.1 89.5% 第一。跨 CLI/IDE/云/GitHub 最全。"},
      {name:"opencode", model:"任意（BYOK，75+ 供应商）", price:"开源免费，只付模型费", tb:null, sv:null,
       t:{上手:"C",开源:"S"},
       note:"星标最多的开源编码 Agent（约 193K，MIT）；自带并行子代理、可换任意模型、可本地/自托管。能力取决于你选的底层模型，灵活度最高。"},
      {name:"Cursor", model:"前沿模型（可换）", price:"$20/月 + 用量", tb:null, sv:74.1,
       t:{上手:"A",开源:"—"},
       note:"VS Code 分支，编辑器内最顺手：Composer 多文件编辑、最高 8 个并行 Agent。适合不想碰命令行的交互式编码。"},
      {name:"Gemini CLI", model:"Gemini 3.1 Pro / 3.8 Flash", price:"免费额度大（约 1000 请求/天）", tb:70.7, sv:80.6,
       t:{上手:"B",开源:"—"},
       note:"免费、零成本入门命令行 AI 编码；SWE-bench V 80.6%、Terminal-Bench 70.7%。轻度任务足够，重度不如前几位。"},
      {name:"GitHub Copilot", model:"多模型", price:"Pro $10/月起（最便宜付费）", tb:null, sv:null,
       t:{上手:"A",开源:"—"},
       note:"IDE 原生、issue→PR 自动化；按 AI Credit 计费，补全免费。适合已在 GitHub 工作的团队，门槛最低。"},
      {name:"Google Antigravity", model:"Gemini 3.5/3.8 Flash", price:"AI Pro $19.99/月", tb:71.2, sv:79.4,
       t:{上手:"A",开源:"—"},
       note:"2026 最技术激进的 IDE：多智能体编排、内置 Chromium 浏览器、约 289 tok/s（Opus 4.8 的 4 倍）。快但深推理不如 Claude Code。"},
      {name:"Cline / Aider", model:"任意（BYOK）", price:"开源免费，只付模型费", tb:null, sv:null,
       t:{上手:"B",开源:"S"},
       note:"开源、Git 原生、按需付费模型。Aider 偏结对编程+自动提交，Cline 偏 VS Code 内自主编辑。零成本试水 Agent 编码的好选择。"}
    ],
    combos: [
      {name:"Claude Code + Claude Fable 5 / Opus 5", score:"S",
       note:"代码 + Agent 综合最强：SWE-bench Verified 95%（Fable 5），Terminal-Bench 89.1%。要最强质量、不怕烧 token 选它。"},
      {name:"Codex CLI + GPT-5.6 Sol", score:"S",
       note:"Terminal-Bench 89.5% 第一，后台并行 PR、跨端体验最好。OpenAI 生态 / 要异步批量任务选它。"},
      {name:"opencode + 任意模型（如 Claude/GPT/Gemini/本地）", score:"A",
       note:"灵活度与性价比之王：自由换模型、成本低、开源可自托管。战斗力 ≈ 你选的底层模型 + 它的 harness。"},
      {name:"Cursor + 前沿模型", score:"A",
       note:"编辑器内最顺手，多文件编辑强。要在 IDE 里交互式写代码而非整任务外包选它。"},
      {name:"Google Antigravity + Gemini", score:"A",
       note:"最快吞吐（约 289 tok/s）、多智能体编排。重速度轻深推理的迭代循环选它。"},
      {name:"Gemini CLI + Gemini 3.1/3.8", score:"B",
       note:"免费额度大、零成本。轻度脚本/学习阶段够用，重度工程不推荐。"},
      {name:"GitHub Copilot + 多模型", score:"B",
       note:"最便宜付费、IDE 原生、issue→PR。团队已在 GitHub 且要低门槛选它。"}
    ],
    tables: {
      aa: {title:"Artificial Analysis 智能指数 v4.3 Top15（满分≈53，2026-09-25 复核）", unit:"分", rows:[
        ["Claude Opus 5.5",58],["Claude Fable 5.1",53],["GPT-6 Astra",53],["Claude Opus 5",51],["Claude Fable 5",50],
        ["Muse Spark 1.3",48],["Grok 4.7",46],["GLM-5.3",45],["Grok 4.6",44],["Kimi K3",44],
        ["GLM-5.3-Flash",42],["Gemini 3.8 Flash",41],["Qwen3.8 (2.4T)",40],["DeepSeek V4.1-Flash",40],
        ["DeepSeek V4 Pro",36]
      ]},
      tb: {title:"Terminal-Bench 2.1 Top10（旧版口径，2026-09；⚠ 官方 8/29 已升级 v4.0，AA v4.3 起改用 TB4.0：Astra 59.1 > Fable 5.1 52.0 > Opus 5 49.0 > GPT-5.6 Sol 39.9）", unit:"%", rows:[
        ["Claude Fable 5.1",91.4],["GPT-6 Astra",89.9],["GPT-5.6 Sol",89.5],["Claude Opus 5",89.1],
        ["Grok 4.6",88.4],["GPT-5.6 Terra",88.0],["Gemini 3.8 Flash",87.6],["Kimi K3",85.0],
        ["GLM-5.3-Flash",84.3],["DeepSeek V4 Pro",78.7]
      ]},
      swe: {title:"SWE-bench（真实 GitHub 修 bug，agent 配对，2026-08）", unit:"%", rows:[
        ["Claude Code + Fable 5 — Verified",95.0],
        ["Claude Code + Fable 5 — Pro",80.3],
        ["Codex + GPT-5.5 — Verified",88.7],
        ["Codex + GPT-5.5 — Pro",58.6],
        ["Claude Code + Opus 4.8 — Verified",88.6],
        ["Gemini CLI + Gemini 3.1 Pro — Verified",80.6],
        ["Gemini CLI + Gemini 3.1 Pro — Pro",54.2],
        ["Codex + GPT-5.6 Sol — Terminal-Bench 2.1",89.5]
      ]}
    }
  };
